theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: kramdown
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty 

plugins:
  - jekyll-toc

collections:
  blogs:
    output: true
    permalink: /:collection/:name/


  