theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts: { preview: false }
  syntax_highlighter: rouge
permalink: pretty 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-toc

collections:
  blogs:
    output: true
    permalink: /:collection/:name/


  